### PR TITLE
Made fetch-deps.sh executable.

### PR DESCRIPTION
**Pull request by raineorshine**

### CODE REVIEW

**Comment by jfdm** [comment]
TBH i would rather not have the script executable by default; this is purely a personal choice. I understand why people would want to make such scripts executable but I would like to keep the annoying barrier for now.

**Comment by raineorshine** [comment]
Ah, okay, thanks for the explanation. I was thinking it would make the installation of nested dependencies easier, for example json-config, idris-containers, etc. As it is, one has has to understand the error that is occurring and then find the right nested folder to chmod the nested fetch-deps. Would you prefer a PR to the README to help communicate these steps to users? Thanks!

**Comment by jfdm** [comment]
Ah, now I understand. You are looking to install dependencies of dependencies. I that case I suggest checking out one of my other projects: jfdm/smokehill This may help.

**Comment by raineorshine** [comment]
Thanks, I'll check it out!

**Pull request closed without merging**
