### PR TITLE
Implement Functor, Foldable & Traversable for Dict

### LINKED ISSUE #23: Traversable instance for Dict
Would you be up for a `Traversable` Instance for `Dict` over the values in the dictionary?
I defined it locally as:
```idris
Ord a => Functor (Dict a) where 
  map func x = fromList $ (\(a, b) => (a, func b)) <$> toList x
Ord a => Foldable (Dict a) where   
  foldr func = foldr $ const func
Ord a => Traversable (Dict a) where 
  traverse f x = fromList <$> (traverse (\(a, b) => (MkPair a) <$> f b) $ Data.AVL.Dict.toList x)
```

### PR DESCRIPTION
**Pull request by mgttlinger**
Fixes #23

### CODE REVIEW

**Comment by jfdm** [comment]
Not to sound like a picky person, is it possible that some simple tests be added to the test suite. Aside from that thanks for the PR.

**Comment by mgttlinger** [comment]
What properties would you want to see tested?

**Comment by jfdm** [comment]
Primarily functional correctness of the implementation's. This is to act as a sanity check that they do what they are supposed to do.

**Comment by mgttlinger** [comment]
Ok, I will write some test later this week.

**Comment by jfdm** [comment]
I'm going to merge this regardless of tests. If you can find time later to add them then great, if not I'll add some later this week.

**Comment by mgttlinger** [comment]
Yeah, sorry rather busy at the moment due to paper deadlines but I will get back to this when I get time

**Pull request merged**
